### ISSUE TITLE
File Sender Protocol

### ISSUE THREAD

**Issue by ExtraGravity** [beaesguerra/AgniMessenger#27]
For sending files, the protocol that we have is very weak, there is no acknowledgement whether we actually want the file or not.  Any thoughts? @jeinglis @beaesguerra @mfalthaw

**Comment by beaesguerra** [comment]
What would determine if the file was wanted or not?

**Comment by ExtraGravity** [comment]
We'd probably send an acknowledgement message from the recipient.

**Comment by beaesguerra** [comment]
Yeah, it would be a good idea to wait for the recipient to accept a file first before sending it
