### ISSUE TITLE
Client Message Receiver Connection Logic

### ISSUE THREAD

**Issue by ExtraGravity** [beaesguerra/AgniMessenger#33]
Message receiver needs to have it's `run` method implemented.

The run method is a threaded function that waits for messages from it's `tcpSocket`. Every message that it receives, it checks its message type, then passes the entire message onto the corresponding Receiver. This also means that the `MessageReceiver` needs reference to each of the receivers. It's constructor will need to be updated. 

On hold until PR #28 is merged.

**Comment by ExtraGravity** [comment]
For testing, we should implement the `main` method for this class. The main method will be a manual test where it will connect to a server through command line arguments and we can receive messages. We can then send messages from the server to verify that the `MessageReceiver` is receiving messages.

**Comment by mfalthaw** [comment]
created pr
