### ISSUE TITLE
Client Receiver Methods

### ISSUE THREAD

**Issue by ExtraGravity** [beaesguerra/AgniMessenger#9]
We need to add stubs for all the client receiver classes. Files involved are:

`ChatReceiver.java`
`FileReceiver.java`
`HeartbeatReceiver.java`
`InformationReceiver.java`
`MessageParser.java`
`ReceiverListener.java`
`StatusReceiver.java`

**Comment by mfalthaw** [comment]
I created the ones in the ClientInteractionUml, should I add more?
